name: Deploy in Heroku

on:
  workflow_dispatch:

jobs:
  deploy_in_heroku:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run tests
        run: mvn test
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=registry.heroku.com/$HEROKU_APP/web
      - name: Login in Heroku container registry
        run: heroku container:login
      - name: Push image to Heroku Registry
        run: docker push registry.heroku.com/$HEROKU_APP/web
      - name: Login in Heroku
        run: heroku container:login
      - name: Deploy to Heroku
        run: heroku container:release web
